export const GET_FAQS_REQUEST = 'GET_FAQS_REQUEST'
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS'
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL'
export const FAQS_RESET = 'FAQS_RESET'

export const ADD_FAQ_REQUEST = 'ADD_FAQ_REQUEST'
export const ADD_FAQ_SUCCESS = 'ADD_FAQ_SUCCESS'
export const ADD_FAQ_FAIL = 'ADD_FAQ_FAIL'
export const ADD_FAQ_RESET = 'ADD_FAQ_RESET'

export const UPDATE_FAQ_REQUEST = 'UPDATE_FAQ_REQUEST'
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS'
export const UPDATE_FAQ_FAIL = 'UPDATE_FAQ_FAIL'
export const UPDATE_FAQ_RESET = 'UPDATE_FAQ_RESET'

export const DELETE_FAQ_REQUEST = 'DELETE_FAQ_REQUEST'
export const DELETE_FAQ_SUCCESS = 'DELETE_FAQ_SUCCESS'
export const DELETE_FAQ_FAIL = 'DELETE_FAQ_FAIL'
export const DELETE_FAQ_RESET = 'DELETE_FAQ_RESET'

//Query Variable
export const GET_QUERIES_REQUEST = 'GET_QUERIES_REQUEST'
export const GET_QUERIES_SUCCESS = 'GET_QUERIES_SUCCESS'
export const GET_QUERIES_FAIL = 'GET_QUERIES_FAIL'
export const QUERIES_RESET = 'QUERIES_RESET'

export const REPLY_QUERY_REQUEST = 'REPLY_QUERY_REQUEST'
export const REPLY_QUERY_SUCCESS = 'REPLY_QUERY_SUCCESS'
export const REPLY_QUERY_FAIL = 'REPLY_QUERY_FAIL'
export const REPLY_QUERY_RESET = 'REPLY_QUERY_RESET'

export const CLOSE_QUERY_REQUEST = 'CLOSE_QUERY_REQUEST'
export const CLOSE_QUERY_SUCCESS = 'CLOSE_QUERY_SUCCESS'
export const CLOSE_QUERY_FAIL = 'CLOSE_QUERY_FAIL'
export const CLOSE_QUERY_RESET = 'CLOSE_QUERY_RESET'

export const SELECTED_TAB = 'SELECTED_TAB'