export const PRICE_GUIDE_REQUEST = 'PRICE_GUIDE_REQUEST'
export const PRICE_GUIDE_SUCCESS = 'PRICE_GUIDE_SUCCESSS'
export const PRICE_GUIDE_FAIL = 'PRICE_GUIDE_FAIL'
export const PRICE_GUIDE_RESET = 'PRICE_GUIDE_RESET'

export const PRICE_GUIDE_UPDATE_REQUEST = 'PRICE_GUIDE_UPDATE_REQUEST'
export const PRICE_GUIDE_UPDATE_SUCCESS = 'PRICE_GUIDE_UPDATE_SUCCESSS'
export const PRICE_GUIDE_UPDATE_FAIL = 'PRICE_GUIDE_UPDATE_FAIL'
export const PRICE_GUIDE_UPDATE_RESET = 'PRICE_GUIDE_UPDATE_RESET'