export const SERVICES_REQUEST = 'SERVICES_REQUEST'
export const SERVICES_SUCCESS = 'SERVICES_SUCCESSS'
export const SERVICES_FAIL = 'SERVICES_FAIL'
export const SERVICES_RESET = 'SERVICES_RESET'

export const SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST'
export const SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESSS'
export const SERVICE_DETAILS_FAIL = 'SERVICE_DETAILS_FAIL'
export const SERVICE_DETAILS_RESET = 'SERVICE_DETAILS_RESET'

export const CHANGE_SERVICE_STATUS_REQUEST = 'CHANGE_SERVICE_STATUS_REQUEST'
export const CHANGE_SERVICE_STATUS_SUCCESS = 'CHANGE_SERVICE_STATUS_SUCCESSS'
export const CHANGE_SERVICE_STATUS_FAIL = 'CHANGE_SERVICE_STATUS_FAIL'
export const CHANGE_SERVICE_STATUS_RESET = 'CHANGE_SERVICE_STATUS_RESET'