export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL'
export const GET_NOTIFICATIONS_RESET = 'GET_NOTIFICATIONS_RESET'

export const SHOW_UNREAD_NOTIFICATIONS_REQUEST = 'SHOW_UNREAD_NOTIFICATIONS_REQUEST'
export const SHOW_UNREAD_NOTIFICATIONS_SUCCESS = 'SHOW_UNREAD_NOTIFICATIONS_SUCCESS'
export const SHOW_UNREAD_NOTIFICATIONS_FAIL = 'SHOW_UNREAD_NOTIFICATIONS_FAIL'
export const SHOW_UNREAD_NOTIFICATIONS_RESET = 'SHOW_UNREAD_NOTIFICATIONS_RESET'

export const MARKAS_READ_NOTIFICATIONS_REQUEST = 'MARKAS_READ_NOTIFICATIONS_REQUEST'
export const MARKAS_READ_NOTIFICATIONS_SUCCESS = 'MARKAS_READ_NOTIFICATIONS_SUCCESS'
export const MARKAS_READ_NOTIFICATIONS_FAIL = 'MARKAS_READ_NOTIFICATIONS_FAIL'
export const MARKAS_READ_NOTIFICATIONS_RESET = 'MARKAS_READ_NOTIFICATIONS_RESET'

export const UNREAD_COUNTER_REQUEST = 'UNREAD_COUNTER_REQUEST'
export const UNREAD_COUNTER_SUCCESS = 'UNREAD_COUNTER_SUCCESS'
export const UNREAD_COUNTER_FAIL = 'UNREAD_COUNTER_FAIL'
export const UNREAD_COUNTER_RESET = 'UNREAD_COUNTER_RESET'