export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESSS'
export const TRANSACTIONS_FAIL = 'TRANSACTIONS_FAIL'
export const TRANSACTIONS_RESET = 'TRANSACTIONS_RESET'