export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESSS'
export const TRANSACTIONS_FAIL = 'TRANSACTIONS_FAIL'
export const TRANSACTIONS_RESET = 'TRANSACTIONS_RESET'

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST'
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESSS'
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL'
export const TRANSACTION_DETAILS_RESET = 'TRANSACTION_DETAILS_RESET'

export const TRANSACTION_REVENUE_REQUEST = 'TRANSACTION_REVENUE_REQUEST'
export const TRANSACTION_REVENUE_SUCCESS = 'TRANSACTION_REVENUE_SUCCESSS'
export const TRANSACTION_REVENUE_FAIL = 'TRANSACTION_REVENUE_FAIL'
export const TRANSACTION_REVENUE_RESET = 'TRANSACTION_REVENUE_RESET'