export const BOOKINGS_REQUEST = 'BOOKINGS_REQUEST'
export const BOOKINGS_SUCCESS = 'BOOKINGS_SUCCESSS'
export const BOOKINGS_FAIL = 'BOOKINGS_FAIL'
export const BOOKINGS_RESET = 'BOOKINGS_RESET'

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESSS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'
export const BOOKING_DETAILS_RESET = 'BOOKING_DETAILS_RESET'