export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST'
export const CUSTOMERS_SUCCESS = 'CUSTOMERS_SUCCESSS'
export const CUSTOMERS_FAIL = 'CUSTOMERS_FAIL'
export const CUSTOMERS_RESET = 'CUSTOMERS_RESET'

export const CUSTOMER_BLOCK_UNBLOCK_REQUEST = 'CUSTOMER_BLOCK_UNBLOCK_REQUEST'
export const CUSTOMER_BLOCK_UNBLOCK_SUCCESS = 'CUSTOMER_BLOCK_UNBLOCK_SUCCESSS'
export const CUSTOMER_BLOCK_UNBLOCK_FAIL = 'CUSTOMER_BLOCK_UNBLOCK_FAIL'
export const CUSTOMER_BLOCK_UNBLOCK_RESET = 'CUSTOMER_BLOCK_UNBLOCK_RESET'

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESSS'
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL'
export const CUSTOMER_DETAILS_RESET = 'CUSTOMER_DETAILS_RESET'