export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST'
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS'
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL'
export const REPORTS_RESET = 'REPORTS_RESET'

export const REPLY_REPORT_REQUEST = 'REPLY_REPORT_REQUEST'
export const REPLY_REPORT_SUCCESS = 'REPLY_REPORT_SUCCESS'
export const REPLY_REPORT_FAIL = 'REPLY_REPORT_FAIL'
export const REPLY_REPORT_RESET = 'REPLY_REPORT_RESET'

export const CLOSE_REPORT_REQUEST = 'CLOSE_REPORT_REQUEST'
export const CLOSE_REPORT_SUCCESS = 'CLOSE_REPORT_SUCCESS'
export const CLOSE_REPORT_FAIL = 'CLOSE_REPORT_FAIL'
export const CLOSE_REPORT_RESET = 'CLOSE_REPORT_RESET'

export const SELECTED_TAB = 'SELECTED_TAB'