export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET'

export const VERIFY_PASSWORD_REQUEST = 'VERIFY_PASSWORD_REQUEST'
export const VERIFY_PASSWORD_SUCCESS = 'VERIFY_PASSWORD_SUCCESS'
export const VERIFY_PASSWORD_FAIL = 'VERIFY_PASSWORD_FAIL'
export const VERIFY_PASSWORD_RESET = 'VERIFY_PASSWORD_RESET'

export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST'
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS'
export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL'
export const CHANGE_EMAIL_RESET = 'CHANGE_EMAIL_RESET'

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL'
export const FILE_UPLOAD_RESET = 'FILE_UPLOAD_RESET'

export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST'
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS'
export const VIEW_PROFILE_FAIL = 'VIEW_PROFILE_FAIL'
export const VIEW_PROFILE_RESET = 'VIEW_PROFILE_RESET'