export const GET_COUNTER_REQUEST = 'GET_COUNTER_REQUEST'
export const GET_COUNTER_SUCCESS = 'GET_COUNTER_SUCCESS'
export const GET_COUNTER_FAIL = 'GET_COUNTER_FAIL'
export const COUNTER_RESET = 'COUNTER_RESET'